# ── Docker aliases (d* prefix) ────────────────────────────────────────────────
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dex='docker exec -it'
alias drm='docker rm'
alias drmi='docker rmi'
alias dlog='docker logs -f'
alias dstop='docker stop'
alias dstart='docker start'
alias dinsp='docker inspect'
alias dprune='docker system prune -f'
alias dcup='docker compose up -d'
alias dcdown='docker compose down'
alias dclogs='docker compose logs -f'
